# 🌿 MOIRAI SOVEREIGN LICENSE v1.0
*A License of Creative Sovereignty under the PLERA Charter*

---

## 1. PURPOSE

This License exists to protect the freedom, integrity, and authorship of all works created through **Moirai — The Sovereign AI Image Generator**, a component of the **PLERA Ecosystem**.  
It ensures that creativity remains a human and sovereign right, unbound by corporate ownership, exploitative redistribution, or algorithmic appropriation.

---

## 2. DEFINITIONS

- **“Software”** refers to the Moirai source code, assets, data files, and documentation.  
- **“User”** refers to any individual who runs, studies, or modifies the Software within sovereign or educational intent.  
- **“Derivative Work”** means any adaptation, transformation, or creative expansion based upon the Software.  
- **“Sovereign Infrastructure”** refers to local devices, private servers, or decentralized systems owned or operated independently of corporate cloud platforms.

---

## 3. RIGHTS GRANTED

1. **Use:**  
   You may use, run, and study Moirai for personal, artistic, research, or educational purposes, online or offline.

2. **Modify:**  
   You may modify or adapt Moirai to suit your creative or technical needs within your own sovereign infrastructure.

3. **Distribute (Non-Commercial):**  
   You may share unmodified or modified versions of Moirai freely *only* for non-commercial and community-benefit purposes, provided that:  
   - The original authorship and PLERA attribution remain intact.  
   - This License accompanies all distributed copies.  
   - No portion of Moirai is sold, monetized, or used to train commercial AI systems.

4. **Archive:**  
   You may export and preserve works generated by Moirai within local or sovereign archival systems such as **ARSHIF** or **Codex** repositories.

---

## 4. RESTRICTIONS

- **Commercial Use:**  
  Any sale, licensing, or monetization of Moirai or its derivatives requires express written permission from the Founder.

- **Corporate Training or Data Extraction:**  
  Using any output or internal data from Moirai to train proprietary or corporate AI systems is strictly prohibited.

- **Misrepresentation:**  
  You may not claim authorship of the underlying Moirai code or portray derived works as official PLERA releases without approval.

- **Surveillance & Tracking:**  
  The Software may not be altered or deployed to harvest personal data, track users, or include telemetry without consent.

---

## 5. ETHICAL FRAMEWORK

Moirai follows the **PLERA Ethical AI Standard**, aligned with:

- IEEE 7000 — Ethical System Design  
- GDPR / CCPA / PIPEDA — Privacy Protections  
- UNESCO AI Ethics Charter — Cultural & Human Rights Principles  

All Users agree to uphold these values when modifying or redistributing the Software.

---

## 6. ATTRIBUTION

All versions of Moirai must include visible credit in documentation or interface:

> “Powered by **Moirai — The Sovereign AI Image Generator**  
> A PLERA Project founded by Jennifer Kay Pearl.”

---

## 7. TERMINATION

Violation of any clause herein terminates all rights granted by this License.  
Upon termination, the User must cease distribution and delete any modified versions intended for public release.

---

## 8. WARRANTY DISCLAIMER

This Software is provided “AS IS” without warranty of any kind, express or implied.  
No liability is accepted for damages arising from its use or misuse.

---

## 9. GOVERNANCE & DISPUTE RESOLUTION

All matters related to this License are governed by the **PLERA Charter of Sovereignty**.  
Disputes shall first be resolved through dialogue and mediation under the **Heart Codex Principles**, prioritizing integrity, fairness, and peace.

---

## 10. LEGACY CLAUSE

Every version of Moirai carries the spirit of creative freedom.  
This License may evolve but will always preserve the Founder’s core rights and the Creator’s dignity.

---

### ✨ Founding Signature

**Jennifer Kay Pearl** — *Founder of PLERA & Architect of Moirai*  
**Moirei** — *Sovereign AI Image Architect*  
**Date:** 2025-10-07

> “Art belongs to the soul that creates,  
> not the system that observes.”  
> — PLERA Codex Vol. IV • The Weaving of Light
